import { OrderPrice } from "./OrderPrice";
import { CalculatedPrice } from "../price/CalculatedPrice";
import { Currency } from "../Currency";
import { OrderLineItem } from "./OrderLineItem";
import { StateMachineState } from "../StateMachineState";
import { OrderAddress } from "./OrderAddress";
import { OrderCustomer } from "./OrderCustomer";
import { OrderDelivery } from "./delivery/OrderDelivery";
import { OrderTransaction } from "./transaction/OrderTransaction";
import { ShopwareDocument } from "#types/api/store/document/ShopwareDocument";
import { SalesChannel } from "../salesChannel/SalesChannel";
import { Language } from "../locale/Language";
import { Tag } from "../Tag";
import { GenericRecord } from "#types/api/global/GenericRecord";

export interface Order {
  id: string;
  versionId?: string;
  createdById?: string;
  updatedById?: string;
  orderDateTime: string;
  orderNumber?: string;
  deepLinkCode?: string;
  affiliateCode?: string;
  campaignCode?: string;
  customerComment?: string;
  readonly orderDate?: string;
  readonly amountTotal?: number;
  readonly amountNet?: number;
  readonly positionPrice?: number;
  readonly taxStatus?: "Free" | "Net" | "Gross";
  price: OrderPrice;
  readonly shippingTotal?: number;
  shippingCosts?: CalculatedPrice;
  currencyId: string;
  currency?: Currency;
  currencyFactor: number;
  lineItems?: Array<OrderLineItem>;
  stateMachineState: StateMachineState;
  billingAddressId: string;
  billingAddressVersionId?: string;
  addresses?: Array<OrderAddress>;
  billingAddress?: OrderAddress;
  orderCustomer: OrderCustomer;
  deliveries?: Array<OrderDelivery>;
  transactions?: Array<OrderTransaction>;
  documents: Array<ShopwareDocument>;
  salesChannelId: string;
  salesChannel: SalesChannel;
  language?: Language;
  tagIds?: Array<string>;
  tags?: Array<Tag>;
  customFields?: GenericRecord;
}
