import { OrderPrice } from "./OrderPrice";
import { CalculatedPrice } from "../price/CalculatedPrice";
import { GenericRecord } from "#types/api/global/GenericRecord";
import { StateMachineState } from "../StateMachineState";
import { OrderCustomer } from "./OrderCustomer";
import { Currency } from "../Currency";
import { Language } from "../locale/Language";
import { OrderAddress } from "./OrderAddress";
import { OrderDelivery } from "./delivery/OrderDelivery";
import { OrderLineItem } from "./OrderLineItem";
import { OrderTransaction } from "./transaction/OrderTransaction";
import { ShopwareDocument } from "#types/api/store/document/ShopwareDocument";
import { Tag } from "../Tag";

export interface Order {
  id: string;
  versionId?: string;
  orderNumber?: string;
  billingAddressId: string;
  billingAddressVersionId?: string;
  currencyId: string;
  languageId: string;
  salesChannelId: string;
  orderDateTime: string;
  readonly orderDate?: string;
  price: OrderPrice;
  readonly amountTotal?: number;
  readonly amountNet?: number;
  readonly positionPrice?: number;
  readonly taxStatus?: "Free" | "Net" | "Gross";
  shippingCosts?: CalculatedPrice;
  readonly shippingTotal?: number;
  currencyFactor: number;
  deepLinkCode?: string;
  affiliateCode?: string;
  campaignCode?: string;
  customerComment?: string;
  source?: string;
  customFields?: GenericRecord;
  createdById?: string;
  updatedById?: string;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  stateMachineState: StateMachineState;
  orderCustomer: OrderCustomer;
  currency?: Currency;
  language?: Language;
  addresses?: Array<OrderAddress>;
  billingAddress?: OrderAddress;
  deliveries?: Array<OrderDelivery>;
  lineItems?: Array<OrderLineItem>;
  transactions?: Array<OrderTransaction>;
  documents: Array<ShopwareDocument>;
  tags?: Array<Tag>;
  extensions?: object;
}
