import { GenericRecord } from "#types/api/global/GenericRecord";
import { CustomerGroup } from "./CustomerGroup";
import { Language } from "../locale/Language";
import { PaymentMethod } from "../PaymentMethod";
import { CustomerAddress } from "./address/CustomerAddress";
import { Salutation } from "../Salutation";
import { Tag } from "../Tag";
import { ProductReview } from "../product/ProductReview";

export interface Customer {
  apiAlias: "customer";
  id: string;
  readonly createdAt: string;
  readonly updatedAt?: string;
  guest?: boolean;
  accountType?: "private" | "business";
  active?: boolean;
  groupId: string;
  group?: CustomerGroup;
  salesChannelId: string;
  customerNumber: string;
  affiliateCode?: string;
  campaignCode?: string;
  languageId: string;
  language?: Language;
  email: string;
  lastPaymentMethodId?: string;
  lastPaymentMethod?: PaymentMethod;
  readonly tagIds?: Array<string>;
  tags?: Array<Tag>;
  salutationId?: string;
  salutation?: Salutation;
  title?: string;
  firstName: string;
  lastName: string;
  company?: string;
  addresses?: Array<CustomerAddress>;
  defaultBillingAddressId: string;
  defaultBillingAddress?: CustomerAddress;
  activeBillingAddress: CustomerAddress;
  defaultShippingAddressId: string;
  defaultShippingAddress?: CustomerAddress;
  activeShippingAddress: CustomerAddress;
  vatIds?: Array<string>;
  readonly lastOrderDate?: string;
  readonly orderCount?: number;
  readonly orderTotalAmount?: number;
  readonly reviewCount?: number;
  productReviews?: Array<ProductReview>;
  customFields?: GenericRecord;
}
