import { Product as StoreApiProduct } from "#types/api/store/product/Product";
import { ProductDownload } from "./ProductDownload";
import { DeliveryTime } from "../DeliveryTime";
import { ProductManufacturer } from "./ProductManufacturer";
import { ProductMedia } from "./ProductMedia";
import { CmsPage } from "../cms/CmsPage";
import { ProductCrossSelling } from "./crossSelling/ProductCrossSelling";
import { ProductSearchKeyword } from "./search/ProductSearchKeyword";
import { ProductReview } from "./ProductReview";
import { MainCategory } from "../category/MainCategory";
import { SeoUrl } from "../seo/SeoUrl";
import { PropertyGroupOption } from "../propertyGroup/PropertyGroupOption";
import { Category } from "../category/Category";
import { Tag } from "../Tag";
import { CalculatedPrice } from "#types/api/store/price/CalculatedPrice";
import { Price } from "#types/api/global";

export type Product = StoreApiProduct & {
  readonly autoIncrement?: number;
  children?: Array<Product>;
  manufacturer?: ProductManufacturer;
  deliveryTime?: DeliveryTime;
  cover?: ProductMedia;
  media?: Array<ProductMedia>;
  tags?: Array<Tag>;
  searchKeywords?: Array<ProductSearchKeyword>;
  customSearchKeywords?: Array<string>;
  options?: Array<PropertyGroupOption>;
  properties?: Array<PropertyGroupOption>;
  productReviews?: Array<ProductReview>;
  crossSellings?: Array<ProductCrossSelling>;
  categories?: Array<Category>;
  categoriesRo?: Array<Category>;
  mainCategories?: Array<MainCategory>;
  seoUrls?: Array<SeoUrl>;
  price?: Array<Price>;
  purchasePrices?: Array<CalculatedPrice>;
  downloads?: Array<ProductDownload>;
  cmsPage?: CmsPage;
};
