import { Product as StoreApiProduct } from "#types/api/store/product/Product";
import { ProductDownload } from "./ProductDownload";
import { DeliveryTime } from "../DeliveryTime";
import { Tax } from "../tax/Tax";
import { ProductManufacturer } from "./ProductManufacturer";
import { Unit } from "../Unit";
import { ProductMedia } from "./ProductMedia";
import { ProductFeatureSet } from "./ProductFeatureSet";
import { CmsPage } from "../cms/CmsPage";
import { ProductCrossSelling } from "./crossSelling/ProductCrossSelling";
import { ProductCrossSellingAssignedProduct } from "./crossSelling/ProductCrossSellingAssignedProduct";
import { ProductConfiguratorSetting } from "./ProductConfiguratorSetting";
import { ProductVisibility } from "./ProductVisibility";
import { ProductSearchKeyword } from "./search/ProductSearchKeyword";
import { ProductReview } from "./review/ProductReview";
import { MainCategory } from "../category/MainCategory";
import { SeoUrl } from "../seo/SeoUrl";
import { OrderLineItem } from "../order/lineItem/OrderLineItem";
import { CustomerWishlist } from "../customer/wishlist/CustomerWishlist";
import { PropertyGroupOption } from "../propertyGroup/PropertyGroupOption";
import { Category } from "../category/Category";
import { ProductStream } from "./stream/ProductStream";
import { Tag } from "../Tag";
import { CustomFieldSet } from "../custom/field/set/CustomFieldSet";
import { CalculatedPrice } from "#types/api/store/price/CalculatedPrice";
import { Price } from "#types/api/global";

export type Product = StoreApiProduct & {
  featureSetId?: string;
  price?: Array<Price>;
  readonly autoIncrement?: number;
  variantRestrictions?: object;
  purchasePrices?: Array<CalculatedPrice>;
  customFieldSetSelectionActive?: boolean;
  slotConfig?: object;
  customSearchKeywords?: Array<object>;
  downloads?: Array<ProductDownload>;
  parent?: Product;
  children?: Array<Product>;
  deliveryTime?: DeliveryTime;
  tax?: Tax;
  manufacturer?: ProductManufacturer;
  unit?: Unit;
  cover?: ProductMedia;
  featureSet?: ProductFeatureSet;
  cmsPage?: CmsPage;
  canonicalProduct?: Product;
  media?: Array<ProductMedia>;
  crossSellings?: Array<ProductCrossSelling>;
  crossSellingAssignedProducts?: Array<ProductCrossSellingAssignedProduct>;
  configuratorSettings?: Array<ProductConfiguratorSetting>;
  visibilities?: Array<ProductVisibility>;
  searchKeywords?: Array<ProductSearchKeyword>;
  productReviews?: Array<ProductReview>;
  mainCategories?: Array<MainCategory>;
  seoUrls?: Array<SeoUrl>;
  orderLineItems?: Array<OrderLineItem>;
  wishlists?: Array<CustomerWishlist>;
  options?: Array<PropertyGroupOption>;
  properties?: Array<PropertyGroupOption>;
  categories?: Array<Category>;
  streams?: Array<ProductStream>;
  categoriesRo?: Array<Category>;
  tags?: Array<Tag>;
  customFieldSets?: Array<CustomFieldSet>;
};
