import { Media as StoreApiMedia } from "#types/api/store/media/Media";
import { Tag } from "../Tag";
import { MediaThumbnail } from "./thumbnail/MediaThumbnail";
import { User } from "../user/User";
import { Category } from "../category/Category";
import { ProductManufacturer } from "../product/ProductManufacturer";
import { ProductMedia } from "../product/ProductMedia";
import { ProductDownload } from "../product/ProductDownload";
import { OrderLineItemDownload } from "../order/lineItem/OrderLineItemDownload";
import { MediaFolder } from "./folder/MediaFolder";
import { PropertyGroupOption } from "../propertyGroup/PropertyGroupOption";
import { MailTemplateMedia } from "../mail/template/MailTemplateMedia";
import { ShopwareDocumentBaseConfig } from "../document/baseConfig/ShopwareDocumentBaseConfig";
import { ShippingMethod } from "../shippingMethod/ShippingMethod";
import { PaymentMethod } from "../paymentMethod/PaymentMethod";
import { ProductConfiguratorSetting } from "../product/ProductConfiguratorSetting";
import { OrderLineItem } from "../order/lineItem/OrderLineItem";
import { CmsBlock } from "../cms/CmsBlock";
import { CmsSection } from "../cms/CmsSection";
import { CmsPage } from "../cms/CmsPage";
import { ShopwareDocument } from "../document/ShopwareDocument";
import { AppPaymentMethod } from "../paymentMethod/AppPaymentMethod";
import { AppShippingMethod } from "../shippingMethod/AppShippingMethod";

export type Media = StoreApiMedia & {
  id: string;
  userId?: string;
  mediaFolderId?: string;
  mimeType?: string;
  readonly fileExtension?: string;
  readonly uploadedAt?: string;
  fileName?: string;
  readonly fileSize?: number;
  readonly metaData?: object;
  readonly mediaType?: object;
  config?: object;
  alt?: string;
  title?: string;
  url?: string;
  path?: string;
  hasFile?: boolean;
  private?: boolean;
  customFields?: object;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  translated?: object;
  extensions?: {
    themes?: {
      links?: { related?: string };
      data?: { type?: string; id?: string };
    };
    themeMedia?: {
      links?: { related?: string };
      data?: { type?: string; id?: string };
    };
  };
  tags?: Array<Tag>;
  thumbnails?: Array<MediaThumbnail>;
  user?: User;
  categories?: Array<Category>;
  productManufacturers?: Array<ProductManufacturer>;
  productMedia?: Array<ProductMedia>;
  productDownloads?: Array<ProductDownload>;
  orderLineItemDownloads?: Array<OrderLineItemDownload>;
  avatarUsers?: Array<User>;
  mediaFolder?: MediaFolder;
  propertyGroupOptions?: Array<PropertyGroupOption>;
  mailTemplateMedia?: Array<MailTemplateMedia>;
  documentBaseConfigs?: Array<ShopwareDocumentBaseConfig>;
  shippingMethods?: Array<ShippingMethod>;
  paymentMethods?: Array<PaymentMethod>;
  productConfiguratorSettings?: Array<ProductConfiguratorSetting>;
  orderLineItems?: Array<OrderLineItem>;
  cmsBlocks?: Array<CmsBlock>;
  cmsSections?: Array<CmsSection>;
  cmsPages?: Array<CmsPage>;
  documents?: Array<ShopwareDocument>;
  appPaymentMethods?: Array<AppPaymentMethod>;
  appShippingMethods?: Array<AppShippingMethod>;
};
