import { Customer as StoreApiCustomer } from "#types/api/store/customer/Customer";
import { CustomerGroup } from "./group/CustomerGroup";
import { SalesChannel } from "../salesChannel/SalesChannel";
import { Language } from "../locale/Language";
import { PaymentMethod } from "../paymentMethod/PaymentMethod";
import { CustomerAddress } from "./CustomerAddress";
import { Salutation } from "../Salutation";
import { OrderCustomer } from "../order/OrderCustomer";
import { Tag } from "../Tag";
import { Promotion } from "../promotion/Promotion";
import { ProductReview } from "../product/review/ProductReview";
import { CustomerRecovery } from "./CustomerRecovery";
import { CustomerWishlist } from "./wishlist/CustomerWishlist";
import { User } from "../user/User";

export type Customer = StoreApiCustomer & {
  readonly autoIncrement?: number;
  remoteAddress?: string;
  requestedGroupId?: string;
  boundSalesChannelId?: string;
  group?: CustomerGroup;
  salesChannel?: SalesChannel;
  language?: Language;
  lastPaymentMethod?: PaymentMethod;
  defaultBillingAddress?: CustomerAddress;
  defaultShippingAddress?: CustomerAddress;
  salutation?: Salutation;
  addresses?: Array<CustomerAddress>;
  orderCustomers?: Array<OrderCustomer>;
  tags?: Array<Tag>;
  promotions?: Array<Promotion>;
  productReviews?: Array<ProductReview>;
  recoveryCustomer?: CustomerRecovery;
  requestedGroup?: CustomerGroup;
  boundSalesChannel?: SalesChannel;
  wishlists?: Array<CustomerWishlist>;
  createdBy?: User;
  updatedBy?: User;
  defaultPaymentMethod?: PaymentMethod;
};
