import { Tag } from "../Tag";
import { OrderCustomer } from "./OrderCustomer";
import { OrderAddress } from "./OrderAddress";
import { OrderDelivery } from "./OrderDelivery";
import { OrderLineItem } from "./OrderLineItem";
import { OrderTransaction } from "./OrderTransaction";
import { GenericRecord } from "#types/storeApi/GenericRecord";
import { CalculatedPrice } from "#types/storeApi/price/CalculatedPrice";
import { StateMachineState } from "#types/storeApi/StateMachineState";
import { Currency } from "#types/storeApi/Currency";
import { Language } from "#types/storeApi/locale/Language";
import { ShopwareDocument } from "#types/storeApi/document/ShopwareDocument";

export type Order = {
  id: string;
  versionId?: string;
  orderNumber?: string;
  billingAddressId: string;
  billingAddressVersionId?: string;
  currencyId: string;
  languageId: string;
  salesChannelId: string;
  orderDateTime: string;
  readonly orderDate: string;
  price: {
    netPrice: number;
    totalPrice: number;
    calculatedTaxes?: object;
    taxRules?: object;
    positionPrice: number;
    rawTotal: number;
    taxStatus: "Free" | "Net" | "Gross";
  };
  readonly amountTotal?: number;
  readonly amountNet?: number;
  readonly positionPrice?: number;
  readonly taxStatus?: "Free" | "Net" | "Gross";
  shippingCosts?: CalculatedPrice;
  readonly shippingTotal?: number;
  currencyFactor: number;
  deepLinkCode?: string;
  affiliateCode?: string;
  campaignCode?: string;
  customerComment?: string;
  source?: string;
  customFields?: GenericRecord;
  createdById?: string;
  updatedById?: string;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  stateMachineState: StateMachineState;
  orderCustomer: OrderCustomer;
  currency?: Currency;
  language?: Language;
  addresses?: Array<OrderAddress>;
  billingAddress?: OrderAddress;
  deliveries?: Array<OrderDelivery>;
  lineItems?: Array<OrderLineItem>;
  transactions?: Array<OrderTransaction>;
  documents: Array<ShopwareDocument>;
  tags?: Array<Tag>;
  extensions?: object;
};
