import { OrderDeliveryPosition } from "./OrderDeliveryPosition";
import { OrderLineItemDownload } from "./OrderLineItemDownload";
import { LineItemPayload } from "#types/storeApi/lineItem/LineItemPayload";
import { CartPriceQuantity } from "#types/storeApi/price/CartPriceQuantity";
import { GenericRecord } from "#types/storeApi/GenericRecord";
import { Media } from "#types/storeApi/media/Media";

export type OrderLineItem = {
  apiAlias: "order_line_item";
  id: string;
  versionId?: string;
  orderId: string;
  orderVersionId?: string;
  productId?: string;
  productVersionId?: string;
  promotionId?: string;
  parentId?: string;
  parentVersionId?: string;
  coverId?: string;
  identifier: string;
  referencedId: string;
  quantity: number;
  label: string;
  payload?: LineItemPayload;
  good?: boolean;
  removable?: boolean;
  stackable?: boolean;
  position?: number;
  states: Array<string>;
  priceDefinition?: CartPriceQuantity;
  unitPrice?: number;
  totalPrice?: number;
  description?: string;
  type?: string;
  customFields?: GenericRecord;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  cover?: Media;
  orderDeliveryPositions?: Array<OrderDeliveryPosition>;
  downloads?: Array<OrderLineItemDownload>;
  parent?: OrderLineItem;
  children: Array<OrderLineItem>;
  extensions?: object;
  translated?: object;
};
