import { CalculatedPrice } from "../price";
import { GenericRecord } from "../GenericRecord";
import { StateMachineState } from "../StateMachineState";
import { OrderAddress, OrderCustomer, OrderDelivery, OrderLineItem, OrderTransaction } from ".";
import { Currency } from "../Currency";
import { Language } from "../locale";
import { ShopwareDocument } from "../document";
import { Tag } from "../Tag";

export type Order = {
  id: string;
  versionId?: string;
  orderNumber?: string;
  billingAddressId: string;
  billingAddressVersionId?: string;
  currencyId: string;
  languageId: string;
  salesChannelId: string;
  orderDateTime: string;
  readonly orderDate: string;
  price: {
    netPrice: number;
    totalPrice: number;
    calculatedTaxes?: object;
    taxRules?: object;
    positionPrice: number;
    rawTotal: number;
    taxStatus: "Free" | "Net" | "Gross";
  };
  readonly amountTotal?: number;
  readonly amountNet?: number;
  readonly positionPrice?: number;
  readonly taxStatus?: "Free" | "Net" | "Gross";
  shippingCosts?: CalculatedPrice;
  readonly shippingTotal?: number;
  currencyFactor: number;
  deepLinkCode?: string;
  affiliateCode?: string;
  campaignCode?: string;
  customerComment?: string;
  source?: string;
  customFields?: GenericRecord;
  createdById?: string;
  updatedById?: string;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  stateMachineState: StateMachineState;
  orderCustomer: OrderCustomer;
  currency?: Currency;
  language?: Language;
  addresses?: Array<OrderAddress>;
  billingAddress?: OrderAddress;
  deliveries?: Array<OrderDelivery>;
  lineItems?: Array<OrderLineItem>;
  transactions?: Array<OrderTransaction>;
  documents: Array<ShopwareDocument>;
  tags?: Array<Tag>;
  extensions?: object;
};
