import { GenericRecord } from "#types/api/global/GenericRecord";
import { Media } from "../media/Media";
import { Tag } from "../Tag";
import { CmsPage } from "../cms/CmsPage";
import { SeoUrlEntity } from "../seo/SeoUrlEntity";

export interface Category {
  apiAlias: "category";
  id: string;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  versionId?: string;
  parentId?: string;
  parent?: Category;
  parentVersionId?: string;
  afterCategoryId?: string;
  afterCategoryVersionId?: string;
  mediaId?: string;
  readonly breadcrumb: Array<object>;
  readonly level?: number;
  readonly path?: string;
  readonly childCount: number;
  children: Array<Category>;
  type: "page" | "folder" | "link";
  productAssignmentType?: "product_stream" | "product";
  linkType?: "external" | "castegory" | "product" | "landing_page";
  media?: Media;
  active?: boolean;
  displayNestedProducts?: boolean;
  visible?: boolean;
  visibleChildCount?: number;
  internalLink?: string;
  externalLink?: string;
  linkNewTab?: boolean;
  cmsPageId?: string;
  cmsPageIdSwitched?: boolean;
  cmsPageVersionId?: string;
  cmsPage?: CmsPage;
  name: string;
  description?: string;
  metaTitle?: string;
  metaDescription?: string;
  keywords?: string;
  seoUrls?: Array<SeoUrlEntity>;
  tags?: Array<Tag>;
  customFields?: GenericRecord;
  translated: Record<string, string>;
}
