import { SalesChannel as StoreApiSalesChannel } from "#types/api/store/salesChannel/SalesChannel";
import { GenericRecord } from "#types/api/global/GenericRecord";
import { Rounding } from "#types/api/global/Rounding";
import { Currency } from "../currency/Currency";
import { Language } from "../locale/Language";
import { Country } from "../country/Country";
import { PaymentMethod } from "../paymentMethod/PaymentMethod";
import { ShippingMethod } from "../shippingMethod/ShippingMethod";
import { SalesChannelType } from "./SalesChannelType";
import { CustomerGroup } from "../customer/group/CustomerGroup";
import { Order } from "../order/Order";
import { Customer } from "../customer/Customer";
import { CmsPage } from "../cms/CmsPage";
import { SalesChannelDomain } from "./SalesChannelDomain";
import { SystemConfig } from "../SystemConfig";
import { Category } from "../category/Category";
import { ProductVisibility } from "../product/ProductVisibility";
import { MailHeaderFooter } from "../mail/MailHeaderFooter";
import { NewsletterRecipient } from "../newsletterRecipient/NewsletterRecipient";
import { NumberRangeSalesChannel } from "../numberRange/NumberRangeSalesChannel";
import { PromotionSalesChannel } from "../promotion/PromotionSalesChannel";
import { ShopwareDocumentBaseConfigSalesChannel } from "../document/baseConfig/ShopwareDocumentBaseConfigSalesChannel";
import { ProductReview } from "../product/review/ProductReview";
import { SeoUrl } from "../seo/SeoUrl";
import { SeoUrlTemplate } from "../seo/SeoUrlTemplate";
import { MainCategory } from "../category/MainCategory";
import { ProductExport } from "../product/ProductExport";
import { SalesChannelAnalytics } from "./SalesChannelAnalytics";
import { LandingPage } from "../cms/landingPage/LandingPage";
import { CustomerWishlist } from "../customer/wishlist/CustomerWishlist";

export type SalesChannel = StoreApiSalesChannel & {
  navigationCategoryVersionId?: string;
  footerCategoryVersionId?: string;
  serviceCategoryVersionId?: string;
  taxCalculationType?: "horizontal" | "vertical";
  accessKey: string;
  configuration?: object;
  active?: boolean;
  hreflangActive?: boolean;
  customFields?: GenericRecord;
  itemRounding?: Rounding;
  totalRounding?: Rounding;
  paymentMethodIds?: Array<string>;
  homeCmsPageId?: string;
  homeCmsPageVersionId?: string;
  homeSlotConfig?: object;
  homeEnabled: boolean;
  homeName?: string;
  homeMetaTitle?: string;
  homeMetaDescription?: string;
  homeKeywords?: string;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  translated?: object;
  extensions?: {
    themes?: {
      links?: { related?: string };
      data?: Array<{ type?: string; id?: string }>;
    };
  };
  currencies?: Array<Currency>;
  languages?: Array<Language>;
  countries?: Array<Country>;
  paymentMethods?: Array<PaymentMethod>;
  shippingMethods?: Array<ShippingMethod>;
  type?: SalesChannelType;
  language?: Language;
  customerGroup?: CustomerGroup;
  currency?: Currency;
  paymentMethod?: PaymentMethod;
  shippingMethod?: ShippingMethod;
  country?: Country;
  orders?: Array<Order>;
  customers?: Array<Customer>;
  homeCmsPage?: CmsPage;
  domains?: Array<SalesChannelDomain>;
  systemConfigs?: Array<SystemConfig>;
  navigationCategory?: Category;
  footerCategory?: Category;
  serviceCategory?: Category;
  productVisibilities?: Array<ProductVisibility>;
  hreflangDefaultDomain?: SalesChannelDomain;
  mailHeaderFooter?: MailHeaderFooter;
  newsletterRecipients?: Array<NewsletterRecipient>;
  numberRangeSalesChannels?: Array<NumberRangeSalesChannel>;
  promotionSalesChannels?: Array<PromotionSalesChannel>;
  documentBaseConfigSalesChannels?: Array<ShopwareDocumentBaseConfigSalesChannel>;
  productReviews?: Array<ProductReview>;
  seoUrls?: Array<SeoUrl>;
  seoUrlTemplates?: Array<SeoUrlTemplate>;
  mainCategories?: Array<MainCategory>;
  productExports?: Array<ProductExport>;
  analytics?: Array<SalesChannelAnalytics>;
  customerGroupRegistrations?: Array<CustomerGroup>;
  landingPages?: Array<LandingPage>;
  boundCustomers?: Array<Customer>;
  wishlists?: Array<CustomerWishlist>;
};
