import { SalesChannel as StoreApiSalesChannel } from "#types/api/store/salesChannel/SalesChannel";
import { Currency } from "../currency/Currency";
import { Language } from "../locale/Language";
import { Country } from "../country/Country";
import { PaymentMethod } from "../paymentMethod/PaymentMethod";
import { ShippingMethod } from "../shippingMethod/ShippingMethod";
import { SalesChannelType } from "./SalesChannelType";
import { CustomerGroup } from "../customer/group/CustomerGroup";
import { CmsPage } from "../cms/CmsPage";
import { SalesChannelDomain } from "./SalesChannelDomain";
import { SystemConfigEntry } from "../SystemConfigEntry";
import { MailHeaderFooter } from "../mail/MailHeaderFooter";
import { MainCategory } from "../category/MainCategory";
import { LandingPage } from "../cms/landingPage/LandingPage";

export type SalesChannel = StoreApiSalesChannel & {
  readonly accessKey: string;
  type?: SalesChannelType;
  taxCalculationType?: "horizontal" | "vertical";
  hreflangDefaultDomainId?: string;
  hreflangDefaultDomain?: SalesChannelDomain;
  domains?: Array<SalesChannelDomain>;
  systemConfigs?: Array<SystemConfigEntry>;
  homeCmsPage?: CmsPage;
  language?: Language;
  languages?: Array<Language>;
  country?: Country;
  countries?: Array<Country>;
  currency?: Currency;
  currencies?: Array<Currency>;
  paymentMethod?: PaymentMethod;
  paymentMethods?: Array<PaymentMethod>;
  shippingMethod?: ShippingMethod;
  shippingMethods?: Array<ShippingMethod>;
  mainCategories?: Array<MainCategory>;
  customerGroupRegistrations?: Array<CustomerGroup>;
  mailHeaderFooterId?: string;
  mailHeaderFooter?: MailHeaderFooter;
  homeEnabled: boolean;
  homeName?: string;
  homeMetaTitle?: string;
  homeMetaDescription?: string;
  homeKeywords?: string;
  homeCmsPageId?: string;
  homeCmsPageVersionId?: string;
  homeSlotConfig?: object;
  landingPages?: Array<LandingPage>;
};
