import { GenericRecord } from "#types/api/global/GenericRecord";
import { CalculatedPrice } from "../price/CalculatedPrice";
import { ProductDownload } from "./ProductDownload";
import { DeliveryTime } from "../DeliveryTime";
import { ProductManufacturer } from "./ProductManufacturer";
import { ProductMedia } from "../media/ProductMedia";
import { CmsPage } from "../cms/CmsPage";
import { ProductCrossSelling } from "./crossSelling/ProductCrossSelling";
import { ProductReview } from "./ProductReview";
import { MainCategory } from "../category/MainCategory";
import { SeoUrlEntity } from "../seo/SeoUrlEntity";
import { PropertyGroupOption } from "#types/api/store/propertyGroup/PropertyGroupOption";
import { ProductStream } from "./ProductStream";
import { Category } from "../category/Category";
import { Tag } from "../Tag";

export interface Product {
  apiAlias: "product";
  id: string;
  versionId?: string;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  parentId?: string;
  parentVersionId?: string;
  readonly childCount?: number;
  children?: Array<Product>;
  active?: boolean;
  manufacturerId?: string;
  productManufacturerVersionId?: string;
  manufacturer?: ProductManufacturer;
  manufacturerNumber?: string;
  productNumber: string;
  readonly displayGroup?: string;
  markAsTopseller?: boolean;
  readonly sales?: number;
  stock: number;
  readonly availableStock?: number;
  restockTime: number;
  purchaseSteps?: number;
  maxPurchase?: number;
  minPurchase?: number;
  purchaseUnit?: number;
  referenceUnit?: number;
  length?: number;
  width?: number;
  height?: number;
  weight?: number;
  deliveryTimeId?: string;
  deliveryTime?: DeliveryTime;
  name: string;
  description?: string;
  coverId?: string;
  cover?: ProductMedia;
  media?: Array<ProductMedia>;
  readonly tagIds?: Array<string>;
  tags?: Array<Tag>;
  readonly propertyIds?: Array<string>;
  properties?: Array<PropertyGroupOption>;
  readonly optionIds?: Array<string>;
  options?: Array<PropertyGroupOption>;
  readonly streamIds?: Array<string>;
  streams?: Array<ProductStream>;
  readonly ratingAverage?: number;
  productReviews?: Array<ProductReview>;
  crossSellings?: Array<ProductCrossSelling>;
  readonly categoryIds?: Array<string>;
  categories?: Array<MainCategory>;
  mainCategories?: Array<MainCategory>;
  metaTitle?: string;
  metaDescription?: string;
  keywords?: string;
  seoUrls?: Array<SeoUrlEntity>;
  seoCategory: Category;
  calculatedPrice: CalculatedPrice;
  calculatedPrices: Array<CalculatedPrice>;
  calculatedCheapestPrice?: CalculatedPrice;
  downloads?: Array<ProductDownload>;
  cmsPageId?: string;
  cmsPageVersionId?: string;
  cmsPage?: CmsPage;
  customFields?: GenericRecord;
  translated?: Record<string, string>;
}
